language: python

python:
  - '3.7'

branches:
  except:
  - gh-pages

install:
  - pip install -U pip
  - make init

script:
  - make test
  - echo "Compiling documentation"
  - make
  - sudo apt-get -qq update
  - sudo apt-get install graphviz
  - python setup.py build_sphinx
