[tool.poetry]
version = '3.0.2'
name = 'ebu-tt-live'
description = 'EBU-TT Part 3 library implementing Specification EBU-3370'
license = "BSD3"
authors = []
readme = "README.md"
packages = [
    { include = "ebu_tt_live" }
    ]
include = [
    { path = "ebu_tt_live.examples/*.txt" },
    { path = "ebu_tt_live.examples/*.json" }
    ]

[tool.poetry.scripts]
ebu-dummy-encoder = 'ebu_tt_live.scripts.ebu_dummy_encoder:main'
ebu-interactive-shell = 'ebu_tt_live.scripts.ebu_interactive_shell:main'
ebu-simple-consumer = 'ebu_tt_live.scripts.ebu_simple_consumer:main'
ebu-simple-producer = 'ebu_tt_live.scripts.ebu_simple_producer:main'
ebu-user-input-consumer = 'ebu_tt_live.scripts.ebu_user_input_consumer:main'
ebu-user-input-forwarder = 'ebu_tt_live.scripts.ebu_user_input_forwarder:main'
ebu-ebuttd-encoder = 'ebu_tt_live.scripts.ebu_ebuttd_encoder:main'
ebu-run = 'ebu_tt_live.scripts.ebu_run:main'
validator = 'ebu_tt_live.scripts.validator:main'

[tool.poetry.dependencies]
python = "^3.11.3"
ipdb = "^0.13.13"
configobj = "^5.0.8"
pyyaml = "^6.0.1"
autobahn = "^22.7.1"
nltk = "^3.8.1"
sortedcontainers = "^2.4.0"
six = "^1.16.0"
sphinxcontrib-plantuml = "^0.26"
sphinx-rtd-theme = "^1.3.0"
pyxb-x = "^1.2.6.1"
configmanners = { git = "https://github.com/twobraids/configmanners.git", rev = "bff28a98cb45dde1b75f52ba3a3ac572a96885eb" }
twisted = "^24.3.0"

[tool.poetry.group.dev.dependencies]
sphinx-autobuild = "^2021.3.14"
recommonmark = "^0.7.1"
pytest = "^7.4.3"
pytest-bdd = "<4"
pytest-cov = "^4.1.0"
pytest-mock = "^3.11.1"
pytest-subtests = "^0.11.0"
pytest-twisted = "^1.14.0"
pytest-runner = "^6.0.1"
Jinja2 = "^3.1.2"
mock = "^5.1.0"
sphinx = "^5.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"