
[pytest]
log_cli = True
testpaths = testing ebu_tt_live
addopts =
    --cov=ebu_tt_live
    --cov-report html
    --cov-report xml
    --cov-report term-missing
markers =
    active
    buffer
    delay
    document
    document
    ebuttd_conversion
    element
    fontSize
    handover
    inherited
    lineHeight
    metadata
    node
    parse_times
    passive
    resolution
    segmentation
    sequence
    simple
    smpte
    styles
    syntax
    times
    timing
    validation
    xsd
