name: Check the tests pass

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Install and build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Setup Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          cache: 'pip'
      - name: Install pip
        run: |
          python -m pip install pip==23.3
        shell: bash
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
        shell: bash
      - name: Generate bindings
        run: |
          pyxbgen --binding-root=./ebu_tt_live/bindings -m __init__ --schema-root=./ebu_tt_live/xsd/ -r -u ebutt_all.xsd
        shell: bash
      - name: Test
        run: |
          pytest
        shell: bash
      - name: Install coveralls
        run: |
          pip install "coveralls<2"
        shell: bash
      - name: Coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          coveralls
